# Generated by Django 5.2.11 on 2026-02-25 23:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['method'], name='payment_method_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['card_type'], name='payment_card_type_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['sale', 'method'], name='payment_sale_method_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['status', 'confirmed_at'], name='sale_status_confirmed_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['cashier', 'created_at'], name='sale_cashier_created_idx'),
        ),
        migrations.AddIndex(
            model_name='saleline',
            index=models.Index(fields=['product'], name='saleline_product_idx'),
        ),
    ]
