# Generated by Codex on 2026-02-28

import uuid
from decimal import Decimal

from django.db import migrations, models
import django.db.models.deletion


def seed_card_commission_plans_and_backfill_payments(apps, schema_editor):
    CardCommissionPlan = apps.get_model("sales", "CardCommissionPlan")
    Payment = apps.get_model("sales", "Payment")

    normal_plan, _ = CardCommissionPlan.objects.update_or_create(
        code="NORMAL",
        defaults={
            "label": "Tarjeta",
            "installments_months": 0,
            "commission_rate": Decimal("0.02"),
            "is_active": True,
            "sort_order": 0,
        },
    )
    msi3_plan, _ = CardCommissionPlan.objects.update_or_create(
        code="MSI_3",
        defaults={
            "label": "3 MSI",
            "installments_months": 3,
            "commission_rate": Decimal("0.0558"),
            "is_active": True,
            "sort_order": 10,
        },
    )

    plans_by_legacy_type = {
        "NORMAL": normal_plan,
        "MSI_3": msi3_plan,
    }

    for payment in Payment.objects.filter(method="CARD").iterator():
        plan = plans_by_legacy_type.get(payment.card_type)
        if not plan:
            continue
        Payment.objects.filter(pk=payment.pk).update(
            card_commission_plan_id=plan.id,
            commission_rate=plan.commission_rate,
            card_plan_code=plan.code,
            card_plan_label=plan.label,
            installments_months=plan.installments_months,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0002_payment_payment_method_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CardCommissionPlan",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("code", models.CharField(max_length=32, unique=True)),
                ("label", models.CharField(max_length=64)),
                ("installments_months", models.PositiveIntegerField(default=0)),
                ("commission_rate", models.DecimalField(decimal_places=4, max_digits=6)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["sort_order", "installments_months", "label"],
                "indexes": [models.Index(fields=["is_active", "sort_order"], name="cardplan_active_sort_idx")],
            },
        ),
        migrations.AddField(
            model_name="payment",
            name="card_commission_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="sales.cardcommissionplan",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="card_plan_code",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="payment",
            name="card_plan_label",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="payment",
            name="commission_rate",
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="installments_months",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(seed_card_commission_plans_and_backfill_payments, migrations.RunPython.noop),
    ]
