# Generated by Django 5.2.11 on 2026-02-25 22:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('layaway', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='customercredit',
            constraint=models.CheckConstraint(condition=models.Q(('balance__gte', 0)), name='customer_credit_balance_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='layaway',
            constraint=models.CheckConstraint(condition=models.Q(('qty__gt', 0)), name='layaway_qty_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='layaway',
            constraint=models.CheckConstraint(condition=models.Q(('total_price__gt', 0)), name='layaway_total_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='layaway',
            constraint=models.CheckConstraint(condition=models.Q(('deposit_amount__gt', 0)), name='layaway_deposit_gt_zero'),
        ),
    ]
