# Generated by Django 5.2.11 on 2026-02-25 23:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('layaway', '0002_customercredit_customer_credit_balance_gte_zero_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='customercredit',
            index=models.Index(fields=['customer_phone'], name='customercredit_phone_idx'),
        ),
        migrations.AddIndex(
            model_name='customercredit',
            index=models.Index(fields=['customer_name', 'customer_phone'], name='customercredit_name_phone_idx'),
        ),
        migrations.AddIndex(
            model_name='layaway',
            index=models.Index(fields=['status', 'expires_at'], name='layaway_status_expires_idx'),
        ),
        migrations.AddIndex(
            model_name='layaway',
            index=models.Index(fields=['customer_phone'], name='layaway_customer_phone_idx'),
        ),
    ]
