# Generated by Django 5.2.11 on 2026-02-25 22:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('investors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_type', models.CharField(choices=[('CAPITAL_DEPOSIT', 'Capital Deposit'), ('CAPITAL_WITHDRAWAL', 'Capital Withdrawal'), ('CAPITAL_TO_INVENTORY', 'Capital to Inventory'), ('INVENTORY_TO_CAPITAL', 'Inventory to Capital'), ('PROFIT_SHARE', 'Profit Share'), ('REINVESTMENT', 'Reinvestment')], max_length=32)),
                ('capital_delta', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('inventory_delta', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('profit_delta', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('reference_type', models.CharField(max_length=64)),
                ('reference_id', models.CharField(max_length=64)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='investors.investor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
