# Generated by Django 5.2.11 on 2026-02-25 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0002_investorassignment_investor_assignment_qty_assigned_gt_zero_and_more'),
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['investor', 'created_at'], name='ledger_investor_created_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['entry_type', 'created_at'], name='ledger_type_created_idx'),
        ),
    ]
