# Generated by Django 5.2.11 on 2026-02-25 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('investors', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='investorassignment',
            constraint=models.CheckConstraint(condition=models.Q(('qty_assigned__gt', 0)), name='investor_assignment_qty_assigned_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='investorassignment',
            constraint=models.CheckConstraint(condition=models.Q(('unit_cost__gte', 0)), name='investor_assignment_unit_cost_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='investorassignment',
            constraint=models.CheckConstraint(condition=models.Q(('qty_sold__gte', 0)), name='investor_assignment_qty_sold_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='investorassignment',
            constraint=models.CheckConstraint(condition=models.Q(('qty_sold__lte', models.F('qty_assigned'))), name='investor_assignment_qty_sold_lte_assigned'),
        ),
    ]
