# Generated by Django 5.2.11 on 2026-03-01 20:43

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def backfill_expense_month_data(apps, schema_editor):
    Expense = apps.get_model('expenses', 'Expense')
    for expense in Expense.objects.all().iterator():
        expense.month_bucket = expense.expense_date.replace(day=1)
        expense.due_date = expense.expense_date
        expense.save(update_fields=['month_bucket', 'due_date'])


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_alter_expense_options_expense_expense_date_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-month_bucket', '-expense_date', '-created_at']},
        ),
        migrations.AddField(
            model_name='expense',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='expense_type',
            field=models.CharField(choices=[('FIXED', 'Fixed'), ('VARIABLE', 'Variable')], db_index=True, default='VARIABLE', max_length=12),
        ),
        migrations.AddField(
            model_name='expense',
            name='month_bucket',
            field=models.DateField(db_index=True, default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='expense',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='paid_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paid_expenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expense',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], db_index=True, default='PAID', max_length=12),
        ),
        migrations.AlterField(
            model_name='expense',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_expenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(backfill_expense_month_data, migrations.RunPython.noop),
        migrations.CreateModel(
            name='FixedExpenseTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=120)),
                ('category', models.CharField(db_index=True, max_length=80)),
                ('default_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('charge_day', models.PositiveSmallIntegerField(default=1)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fixed_expense_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name', 'category'],
            },
        ),
        migrations.AddField(
            model_name='expense',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='expenses.fixedexpensetemplate'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['month_bucket', 'status'], name='expense_month_status_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['expense_type', 'month_bucket'], name='expense_type_month_idx'),
        ),
        migrations.AddConstraint(
            model_name='expense',
            constraint=models.UniqueConstraint(condition=models.Q(('template__isnull', False)), fields=('template', 'month_bucket'), name='expense_template_month_unique'),
        ),
        migrations.AddIndex(
            model_name='fixedexpensetemplate',
            index=models.Index(fields=['is_active', 'category'], name='fixedexp_active_cat_idx'),
        ),
        migrations.AddConstraint(
            model_name='fixedexpensetemplate',
            constraint=models.CheckConstraint(condition=models.Q(('default_amount__gt', 0)), name='fixedexp_amount_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='fixedexpensetemplate',
            constraint=models.CheckConstraint(condition=models.Q(('charge_day__gte', 1), ('charge_day__lte', 28)), name='fixedexp_charge_day_valid'),
        ),
    ]
