# Generated by Django 5.2.11 on 2026-02-25 22:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceImportBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raw_text', models.TextField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PARSED', 'Parsed'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('ERROR', 'Error')], default='DRAFT', max_length=16)),
                ('invoice_number', models.CharField(blank=True, max_length=64, null=True)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('tax', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('parser', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='suppliers.supplierinvoiceparser')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='suppliers.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceImportLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('line_no', models.PositiveIntegerField()),
                ('raw_line', models.TextField()),
                ('parsed_sku', models.CharField(blank=True, max_length=64)),
                ('parsed_name', models.CharField(blank=True, max_length=255)),
                ('parsed_qty', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('parsed_unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('parsed_unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('sku', models.CharField(blank=True, max_length=64)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('qty', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('match_status', models.CharField(choices=[('NEW_PRODUCT', 'New Product'), ('MATCHED_PRODUCT', 'Matched Product'), ('AMBIGUOUS', 'Ambiguous'), ('INVALID', 'Invalid')], default='INVALID', max_length=20)),
                ('is_selected', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='imports.invoiceimportbatch')),
                ('matched_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.product')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('batch', 'line_no'), name='unique_batch_line_no')],
            },
        ),
    ]
