# Generated by Django 5.2.11 on 2026-02-27 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_brand_producttype_product_brand_label_and_more'),
        ('imports', '0002_invoiceimportline_public_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceimportline',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.brand'),
        ),
        migrations.AddField(
            model_name='invoiceimportline',
            name='brand_name',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='invoiceimportline',
            name='product_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.producttype'),
        ),
        migrations.AddField(
            model_name='invoiceimportline',
            name='product_type_name',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
